### ISSUE TITLE
Error to summarizer

### ISSUE THREAD

**Issue by tommoholmes10** [JesusIslam/tldr#2]
it's my code
```go
package main

import (
    "fmt"
    "github.com/JesusIslam/tldr"
    "strings"
)

func main() {
    intoSentences := 3
    words := "loremdkasmsdma skdmlaskldmsla mdaskdlsamskdlasm..............tsk"
    leng := strings.Count(words, ".")
    if leng > 3 {
	    bag := tldr.New()
	    result := bag.Summarize(words, intoSentences)
	    fmt.Println(result)
    }
}
```
when I run this code I get 
```
panic: runtime error: slice bounds out of range
```

**Comment by tommoholmes10** [comment]
Ok I notice what my problem

**Comment by JesusIslam** [comment]
It appears that your sentence `"loremdkasmsdma skdmlaskldmsla mdaskdlsamskdlasm..............tsk"` is count as one sentence only, so it would unsurprisingly crash if it is trying to access to more elements than the slice has.

I'm still trying to make a better tests for this package, so please bear with me.

**Comment by tommoholmes10** [comment]
I change to my code with
```go
package main

import (
    "fmt"
    "github.com/JesusIslam/tldr"
)

func main() {
    intoSentences := 3
    words := "Tas LV Speedy 1201 Mungil Monogram Matang [Semi Super]Produk: Dimensi: 25 x 18 x 15 (panjang x tinggi x tebal)Bahan Luar: kulit LV Monogram lis matang sintetisBahan Dalam: kain berlogo LVDustbag: Ada, warna coklat ada logo LVNomor seri (serial number): AdaTali Panjang: AdaSertifikat: Tidak adaSilahkan yang berminat..............tsk"
	bag := tldr.New()
	result := bag.Summarize(words, intoSentences)
	fmt.Println(result)
}
```
and still get error
```
panic: runtime error: slice bounds out of range
```

**Comment by JesusIslam** [comment]
I've already update the package, can you try it?

Also, that sentence is still count as one sentence.

**Comment by tommoholmes10** [comment]
Oke I'm Checking now,
Are you indonesian?

**Comment by JesusIslam** [comment]
Well, yes I am an Indonesian.

Please let me know the result of the update. Cheers.

**Comment by tommoholmes10** [comment]
still error
this is error message
```
desc  For your classy girl, this classy set from Absorba will add more posh effect t$
panic: runtime error: index out of range

goroutine 27 [running]:
runtime.panic(0x8083c0, 0xb217bc)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/JesusIslam/tldr.symetricDifference(0xc2082156c0, 0x35, 0x35, 0xc20802dba0$
        /root/go/src/github.com/JesusIslam/tldr/tldr.go:508 +0x1a0
github.com/JesusIslam/tldr.(*Bag).createEdges(0xc208040080)
        /root/go/src/github.com/JesusIslam/tldr/tldr.go:492 +0x45a
github.com/JesusIslam/tldr.(*Bag).Summarize(0xc208040080, 0xc208bc3800, 0x169, 0x3, $
        /root/go/src/github.com/JesusIslam/tldr/tldr.go:76 +0x5ef
main.func  015(0x1, 0xc208414030)
        /root/witch-scrapper/crawler.go:437 +0x684
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc2085be0f0, 0x7f51a36c1a50, 0x14)
        /root/go/src/github.com/PuerkitoBio/goquery/iteration.go:7 +0x11a
main.func  016(0x0, 0xc2087794d0)
        /root/witch-scrapper/crawler.go:453 +0x27f
```

**Comment by JesusIslam** [comment]
Hmm, that's very weird. Any sample text that I can use to reproduce this?

**Comment by tommoholmes10** [comment]
Oke wait.
please tell me why error message ```panic: runtime error: index out of range``` ?

**Comment by JesusIslam** [comment]
It is because the program (from this package) is trying to access non-existent element of a slice.

I'll wait for the sample text.

**Comment by tommoholmes10** [comment]
when I get from json and then summarize it, I get error. But when I'm print json text and then summarize it, it's woorking well

**Comment by JesusIslam** [comment]
I'm not really following? What do you mean by that? (You can obviously reply in Indonesian if it is hard to express that in English)

**Comment by tommoholmes10** [comment]
Gini gan, kalau aku ambil data dari json( download json) trus aku summerize dia error. Tapi kalau aku copas text ny dari json ny dia jalan.

**Comment by JesusIslam** [comment]
Seharusnya memang text murni, bukan JSON mas.

**Comment by tommoholmes10** [comment]
tapi kan sudah aku decode mas trus hasil ny juga sudah string

**Comment by JesusIslam** [comment]
Ada contoh stringnya?

**Comment by tommoholmes10** [comment]
ini gan contoh nya
```
Kulit sintetis pada bagian telapak dengan lubang berlubang mikro pada jariTerbuat dari bahan komposit khususJumlah : Satu Pasang (Kanan-Kiri)Warna: HitamUkuran XL Aktual : Panjang Total : 22 cmLebar strap / pengikat : 2 cmpanjang sarung tangan (tidak termasuk strap) : 20 cmReady Stok : 5Note : Warna dan Ukuran tersedia sesuai dengan deskripsi diatasReady stok terupdate
```
kalau di jalanin tanpa ambil dari json ny jalan
tapi klu download trus di summirze gagal

**Comment by JesusIslam** [comment]
Hmmm kok jalan ya disini

```
package main

import (
	"fmt"
	"github.com/JesusIslam/tldr"
)

func main() {
	intoSentences := 1000
	bag := tldr.New()
	result := bag.Summarize("Kulit sintetis pada bagian telapak dengan lubang berlubang mikro pada jariTerbuat dari bahan komposit khususJumlah : Satu Pasang (Kanan-Kiri)Warna: HitamUkuran XL Aktual : Panjang Total : 22 cmLebar strap / pengikat : 2 cmpanjang sarung tangan (tidak termasuk strap) : 20 cmReady Stok : 5Note : Warna dan Ukuran tersedia sesuai dengan deskripsi diatasReady stok terupdate", intoSentences)

	fmt.Println(result)
}
```

```
Output:
$ go run test.go
Kulit sintetis pada bagian telapak dengan lubang berlubang mikro pada jariTerbuat dari bahan komposit khususJumlah : Satu Pasang (Kanan-Kiri)Warna: HitamUkuran XL Aktual : Panjang Total : 22 cmLebar strap / pengikat : 2 cmpanjang sarung tangan (tidak termasuk strap) : 20 cmReady Stok : 5Note : Warna dan Ukuran tersedia sesuai dengan deskripsi diatasReady stok terupdate
```

Sudah pakai update terbaru?

**Comment by tommoholmes10** [comment]
oo ini gan, kalau ada data double quote
```go
package main

import (
"fmt"
"github.com/JesusIslam/tldr"
)

func main() {
	intoSentences := 1000
	bag := tldr.New()
	words := `Jam Tangan Pria "SKMEI 1025" ORIGINAL Simple Pack (No Box)Warna : Black n GreenJenis olahraga: Lari / Sepeda / Renang / SnorklingDial Window Material Type: HardlexCase Material: Aluminum Dial Material Type: ABS MaterialKedalaman Water Resistance: 50 mMovement: DigitalBand Material: RubberLebar tali jam: 20mm to 29mm, Panjang tali jam: 25cmDial Diameter: 4.5 cm100% Original Skmei, bukan OEM apalagi KW.Untuk wilayah jakarta, depok, tangerang, bekasi dapat memasukan keterangan pengiriman melalui Go-jek (tergantung wilayah jangkauan)Kelebihan menggunakan Go-jek :1. Barang cepat sampai di hari yang sama2. Pembelian grosir lebih hemat tanpa memikirkan berat per kilogram, jadi bisa beli lebih banyak 3. Ongkir via pengiriman Go-jek sama dengan ongkir JNE Reguler Rp.9.000,-  (kelebihan biaya pengiriman karena perhitungan berat pengiriman pada saat order akan kami kembalikan pada saat pengiriman)Pengiriman dijamin ekspress saat order di hari kerja (senin - jumat) maksimal order masuk pukul 14.00 WIB resi akan diinput langsung, sangat cocok buat reseller dan dropshipper yang ingin menjual kembali produk kami dengan nama pengirim yang tercantum nama anda :)Selamat berwirausaha`
	if words != ""{
		for {
			words = bag.Summarize(words, intoSentences)
			fmt.Println(words)
		}
	}
}
```

**Comment by tommoholmes10** [comment]
sudah gan.. masih aja error.

**Comment by JesusIslam** [comment]
Sorry it took so long for me to come back here.

This is weird as I couldn't reproduce it over here...
